/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-10-29 13:17:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import pkrent4u.schema.Car;
import pkrent4u.dao.CarDAO;
import java.util.ArrayList;
import pkrent4u.*;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./components/Nav.jsp", Long.valueOf(1698522837160L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("pkrent4u");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("pkrent4u.dao.CarDAO");
    _jspx_imports_classes.add("pkrent4u.schema.Car");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>FAQ</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://cdn.discordapp.com/attachments/965375341071847434/1160730098618601482/image.png?ex=6535b924&is=65234424&hm=02edc80e5cc1c9b7937bdbc00efe262fb24180a3850827d298d32e71ee6a8d8b&\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Animetion.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/global.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Bootstrap.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".rank-math-seo-score {\r\n");
      out.write("	font-family: sans-serif;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	height: 96px;\r\n");
      out.write("	width: 96px;\r\n");
      out.write("	margin: 20px 20px 30px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	background: #eee;\r\n");
      out.write("	-webkit-box-shadow: 1px 1px 1px #bbb;\r\n");
      out.write("	box-shadow: 1px 1px 1px #bbb\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.before-content {\r\n");
      out.write("	margin: 0 0 30px 20px;\r\n");
      out.write("	float: right\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.after-content {\r\n");
      out.write("	margin: 20px 0 30px 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.as-shortcode {\r\n");
      out.write("	display: inline-block\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score .label {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 100px;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	color: #979ea5\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score .score {\r\n");
      out.write("	font-size: 42px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	line-height: 42px;\r\n");
      out.write("	display: block\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score .outof {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	line-height: 12px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	color: rgba(255, 255, 255, 0.7)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score .backlink {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: -94px;\r\n");
      out.write("	left: -12px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	visibility: hidden;\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	padding: 8px 10px;\r\n");
      out.write("	-webkit-transition: .25s all ease;\r\n");
      out.write("	transition: .25s all ease;\r\n");
      out.write("	-webkit-transition-delay: .25s;\r\n");
      out.write("	transition-delay: .25s;\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	color: #a8a8a8;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	-webkit-box-shadow: 0 4px 14px rgba(60, 60, 90, 0.2);\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(60, 60, 90, 0.15)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score .backlink:after {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	bottom: -8px;\r\n");
      out.write("	left: calc(50% - 7px);\r\n");
      out.write("	width: 0;\r\n");
      out.write("	height: 0;\r\n");
      out.write("	content: '';\r\n");
      out.write("	border-width: 8px 7.5px 0 7.5px;\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("	border-color: #fff transparent transparent transparent\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score:hover .backlink {\r\n");
      out.write("	top: -74px;\r\n");
      out.write("	visibility: visible;\r\n");
      out.write("	opacity: 1\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score .poweredby {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #a8a8a8\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score .poweredby a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: #6372b6;\r\n");
      out.write("	border: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.unknown-seo {\r\n");
      out.write("	background: #eee;\r\n");
      out.write("	background: linear-gradient(135deg, #b9b9b9 0%, #989898 100%);\r\n");
      out.write("	-webkit-box-shadow: 1px 1px 1px #bbb;\r\n");
      out.write("	box-shadow: 1px 1px 1px #bbb\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.bad-seo {\r\n");
      out.write("	background: #f8b0a2;\r\n");
      out.write("	background: linear-gradient(135deg, #f8b0a2 0%, #f1938c 100%);\r\n");
      out.write("	-webkit-box-shadow: 1px 1px 1px #e48982;\r\n");
      out.write("	box-shadow: 1px 1px 1px #e48982;\r\n");
      out.write("	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f8b0a2',\r\n");
      out.write("		endColorstr='#f1938c', GradientType=1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.good-seo {\r\n");
      out.write("	background: #fdd07a;\r\n");
      out.write("	background: linear-gradient(135deg, #fdd07a 0%, #fcbe6c 100%);\r\n");
      out.write("	-webkit-box-shadow: 1px 1px 1px #efb463;\r\n");
      out.write("	box-shadow: 1px 1px 1px #efb463;\r\n");
      out.write("	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fdd07a',\r\n");
      out.write("		endColorstr='#fcbe6c', GradientType=1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.great-seo {\r\n");
      out.write("	background: #99d484;\r\n");
      out.write("	background: linear-gradient(135deg, #99d484 0%, #83c97f 100%);\r\n");
      out.write("	-webkit-box-shadow: 1px 1px 1px #5ba857;\r\n");
      out.write("	box-shadow: 1px 1px 1px #5ba857;\r\n");
      out.write("	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#99d484',\r\n");
      out.write("		endColorstr='#83c97f', GradientType=1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-circle .score {\r\n");
      out.write("	margin-top: 22px !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-square {\r\n");
      out.write("	height: 80px;\r\n");
      out.write("	width: 110px;\r\n");
      out.write("	border-radius: 12px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-square .score {\r\n");
      out.write("	margin: 10px 12px;\r\n");
      out.write("	text-align: left\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-square .outof {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-left: -8px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-square .label {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	top: 52px;\r\n");
      out.write("	left: 14px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	color: rgba(255, 255, 255, 0.8)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-square .backlink {\r\n");
      out.write("	left: -5px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-square.before-content {\r\n");
      out.write("	margin-bottom: 20px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rank-math-seo-score.template-square.after-content {\r\n");
      out.write("	margin-bottom: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".theme-twentytwenty .rank-math-seo-score {\r\n");
      out.write("	width: 96px !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".theme-twentytwenty .rank-math-seo-score.template-square {\r\n");
      out.write("	width: 110px !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".theme-twentytwenty .rank-math-seo-score.before-content {\r\n");
      out.write("	margin: 0 auto 30px auto;\r\n");
      out.write("	display: inherit;\r\n");
      out.write("	float: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".theme-twentytwenty .rank-math-seo-score.template-circle .score,\r\n");
      out.write("	.theme-twentytwenty .rank-math-seo-score.template-square .score {\r\n");
      out.write("	transform: translateY(22px)\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("			data-mdb-toggle=\"collapse\" data-mdb-target=\"#navbarSupportedContent\"\r\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<i class=\"fas fa-bars\"></i>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("			<a class=\"navbar-brand mt-2 mt-lg-0\" href=\"/\"> <img\r\n");
      out.write("				src=\"https://cdn.discordapp.com/attachments/965375341071847434/1160730098618601482/image.png\"\r\n");
      out.write("				height=\"32\" alt=\"Rent4U\" loading=\"lazy\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"/miniproject/\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"/miniproject/cars.jsp\">Cars</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"/miniproject/motors.jsp\">Motors</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"/miniproject/contact.jsp\">Contact</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"/miniproject/faq.jsp\">FAQ</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"dropdown\">\r\n");
      out.write("			<a class=\"dropdown-toggle d-flex align-items-center hidden-arrow\"\r\n");
      out.write("				href=\"#\" id=\"navbarDropdownMenuAvatar\" role=\"button\"\r\n");
      out.write("				data-mdb-toggle=\"dropdown\" aria-expanded=\"false\"> <img\r\n");
      out.write("				src=\"https://cdn-icons-png.flaticon.com/512/9703/9703596.png\"\r\n");
      out.write("				class=\"rounded-circle\" height=\"25\"\r\n");
      out.write("				alt=\"Black and White Portrait of a Man\" loading=\"lazy\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("				aria-labelledby=\"navbarDropdownMenuAvatar\">\r\n");
      out.write("				");

				HttpSession ses = request.getSession();
				String username = (String) ses.getAttribute("username");
				
      out.write("\r\n");
      out.write("				");

				if (username != null) {
				
      out.write("\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"/miniproject/Admin/dashboard.jsp\">Rental Dashboard</a></li>\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"/miniproject/Admin/users.jsp\">Add users</a></li>\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"/miniproject/Backend/Logout.jsp\">Logout</a></li>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<li><a class=\"dropdown-item\" href=\"/miniproject/loginpage.jsp\">Login</a></li>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<div class=\"container dashboard-fade pt-4 pb-4\">\r\n");
      out.write("		<h2>รถเช่าคืออะไร</h2>\r\n");
      out.write("		<p>รถเช่า เป็นบริการให้เช่ารถยนต์เพื่อขับใช้\r\n");
      out.write("			โดยมีการตกลงระยะเวลาในการเช่า และราคาเช่ารถ การมัดจำ การรับ-ส่งคืนรถ\r\n");
      out.write("			พร้อมทั้งมีเอกสารประกอบการเช่ารถ\r\n");
      out.write("			เพื่อให้เกิดความมั่นใจได้ทั้งผู้เช่ารถและผู้ให้เช่ารถ</p>\r\n");
      out.write("		<h2>ใครที่จองรถเช่าได้บ้าง</h2>\r\n");
      out.write("		<p>ผู้ที่จองรถเช่า ต้องเป็นไปตามข้อตกลงของการเช่ารถ\r\n");
      out.write("			คือมีอายุถึงตามกำหนดที่ทางผู้ให้บริการรถเช่ากำหนดไว้ เช่น\r\n");
      out.write("			บางที่กำหนดไว้ที่อายุ 21 ปี บางที่กำหนดไว้ที่ 23 ปี เป็นต้น</p>\r\n");
      out.write("		<h2>การเช่ารถระยะสั้น ระยะยาว ต่างกันอย่างไร</h2>\r\n");
      out.write("		<p>การเช่ารถระยะสั้น เป็นการเช่ารถโดยผู้ใช้รถทั่วไป\r\n");
      out.write("			อาจมีการเช่ารถเป็นจำนวนวัน เช่น 1 วัน 3 วัน เป็นต้น\r\n");
      out.write("			ส่วนการเช่ารถระยะยาวมักเป็นการเช่ารถกับในองค์กรใหญ่ๆ\r\n");
      out.write("			ที่มีการตกลงเช่าเป็นระยะเวลาหนึ่ง เช่น หนึ่งเดือน สามเดือน หนึ่งปี\r\n");
      out.write("			เป็นต้น</p>\r\n");
      out.write("		<h2>รถเช่าระหว่างซ่อมคืออะไร</h2>\r\n");
      out.write("		<p>รถเช่าระหว่างซ่อม เป็นการให้บริการรถเช่าในระหว่างที่นำรถไปซ่อม\r\n");
      out.write("			โดยในการตกลงเช่ารถชนิดนี้ จะต้องมีเอกสารการซ่อมรถ เอกสารการเคลมประกัน\r\n");
      out.write("			เพื่อใช้ประกอบการเช่ารถระหว่างซ่อม\r\n");
      out.write("			ซึ่งผู้เช่าจะมีรถไว้ใช้งานในระหว่างที่รถกำลังซ่อมอยู่นั่นเอง</p>\r\n");
      out.write("		<h2>การบล็อกวงเงินบัตรเครดิตคืออะไร</h2>\r\n");
      out.write("		<p>เป็นการกันวงเงินบัตรเครดิตเอาไว้ในระหว่างที่เช่ารถ\r\n");
      out.write("			เหมือนเป็นการมัดจำรถเช่าเอาไว้ก่อน\r\n");
      out.write("			ซึ่งยอดที่บล็อกนั้นจะไม่สามารถใช้ได้จนกว่าจะได้วงเงินคืน\r\n");
      out.write("			โดยอัตราการบล็อกวงเงินบัตรเครดิตนั้นขึ้นอยู่กับเงื่อนไขแต่ละบริษัท\r\n");
      out.write("			รวมถึงรถเช่าที่ใช้ เมื่อถึงกำหนดคืนรถเช่าแล้ว\r\n");
      out.write("			ทางธนาคารจะมีการคืนวงเงินเครดิตดังกล่าว ซึ่งใช้เวลาประมาณ 1-2 สัปดาห์\r\n");
      out.write("			แล้วแต่ธนาคารของบัตรเครดิตนั้นๆ</p>\r\n");
      out.write("		<h2>การคิดราคารถเช่า</h2>\r\n");
      out.write("		<p>การคิดราคารถเช่า โดยส่วนใหญ่จะคิดเป็นวันคือ 24 ชั่วโมง\r\n");
      out.write("			ส่วนราคาเท่าไหร่นั้น จะแล้วแต่รุ่นรถที่ใช้งาน มีตั้งแต่ระดับ เล็กๆ\r\n");
      out.write("			อีโคคาร์ รถเก๋ง รถครอบครัว แล้วแต่ว่าจะเช่าแบบไหน\r\n");
      out.write("			ราคาก็ไล่ระดับขึ้นไป ตั้งแต่หลักร้อยถึงหลักพันนิดๆ ต่อวัน</p>\r\n");
      out.write("		<h2>จะไปรับรถเช่าได้ที่ไหน</h2>\r\n");
      out.write("		<p>ขณะนี้ Rent4U มีสาขารถเช่าให้ท่านไปรับรถมากถึง 13 สาขา\r\n");
      out.write("			ซึ่งครอบคลุมทั้งในพื้นที่กรุงเทพฯ และปริมณฑล\r\n");
      out.write("			รวมไปถึงสาขารถเช่าในสนามบินหลาจุดทั่วประเทศ\r\n");
      out.write("			เพื่อให้ท่านเลือกสาขาที่ใกล้ที่สุดและสะดวกที่สุดในการไปรับรถเช่า</p>\r\n");
      out.write("		<h2>จะตกลงเช่ารถต้องทำอย่างไร</h2>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>เลือกชนิดของรถ รุ่นรถ สถานที่วันเวลาที่รับรถและส่งคืนรถเช่า\r\n");
      out.write("				ผ่านแบบฟอร์มในหน้าเว็บไซต์</li>\r\n");
      out.write("			<li>เมื่อเจ้าหน้าที่ตรวจสอบรถที่ลูกค้าต้องการก็จะยืนยันกลับไปพร้อมแจ้งค่าใช้จ่ายทั้งหมด</li>\r\n");
      out.write("			<li>ลูกค้าส่งสำเนาเอกสารการเช่ารถเช่น สำเนาบัตรประจำตัวประชาชน\r\n");
      out.write("				สำเนาใบขับขี่</li>\r\n");
      out.write("			<li>ชำระเงินตามเงื่อนไขที่ทางศูนย์บริการรถเช่าได้แจ้งไว้\r\n");
      out.write("				อาจมีค่ามัดจำ หรือบล็อกวงเงินบัตรเครดิต\r\n");
      out.write("				ซึ่งต้องดูเงื่อนไขของแต่ละรถเช่าว่าเป็นอย่างไร</li>\r\n");
      out.write("			<li>สามารถไปรับรถเช่าได้ตามกำหนดเวลาที่ตกลงไว้</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<h2>เช่ารถกับ Rent4U ดีกว่ายังไง?</h2>\r\n");
      out.write("		<p>Rent4U ของเรามีความพร้อม\r\n");
      out.write("			ทั้งด้านความเชี่ยวชาญในการจัดการเรื่องรถเช่าให้คุณ\r\n");
      out.write("			พร้อมทั้งคำแนะนำและดูแลคุณทุกขั้นตอน\r\n");
      out.write("			ด้วยมาตรฐานการบริการที่ครอบคลุมและตอบโจทย์ทุกความต้องการของคุณได้อย่างแน่นอน</p>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
